jobs:
- job: Testing_${{ replace(parameters.SERVICENAME, '-', '_') }}
  displayName: Post Deployment API Testing ${{ parameters.SERVICENAME }}
  dependsOn: 
    - Deploy_${{ replace(parameters.SERVICENAME, '-', '_') }}
    - DB_Deploy
  condition: and(eq(variables['API_Test'],'true'), and(and(not(canceled()),not(failed())), and(eq(variables['service_deploy'],'true'), ne(variables['Build.Reason'], 'PullRequest'))))
  cancelTimeoutInMinutes: 1
  variables:
  - name: 'SERVICENAME'
    value: ${{ parameters.SERVICENAME }}
  steps:
    - checkout: CICD_Agent_Portal_NodeJS
    - bash: |
        # Write your commands here
        cd $(System.DefaultWorkingDirectory)/$(SERVICENAME)/configs/$(ENVIRONMENT)
        sed -i -e "s/#username#/$(ADO_AGENT_USERNAME)/g" postman-environment.json
        sed -i -e "s/#password#/$(ADO_AGENT_PASSWORD)/g" postman-environment.json
        
        cat postman-environment.json
      displayName: 'Update the Newman Environment Variables'

    - bash: |
        # Write your commands here
        echo "node version"
        node -v
        echo "newman version"
        newman -v
        cd $(System.DefaultWorkingDirectory)/$(SERVICENAME)/postman-tests/$(ENVIRONMENT)
        collection=`ls *.json`
        for eachfile in $collection
        do
          file="${eachfile/.json/.xml}"   
          echo "$eachfile"
          echo "$file"
          newman run $eachfile -k --reporters cli,junit --reporter-junit-export $file -e $(System.DefaultWorkingDirectory)/$(SERVICENAME)/configs/$(ENVIRONMENT)/postman-environment.json
        ls -al
        done
      displayName: 'Run Newman API Testing'
      condition: succeeded()


    - task: PublishTestResults@2
      displayName: 'Publish Test Results for Newman'
      inputs:
        testResultsFiles: '*.xml'
        failTaskOnFailedTests: true
        searchFolder: '$(System.DefaultWorkingDirectory)/$(SERVICENAME)/postman-tests/$(ENVIRONMENT)'
        mergeTestResults: false
        testRunTitle: 'API_Testing_$(SERVICENAME)_$(ENVIRONMENT)'
        publishRunAttachments: false
      condition: succeededOrFailed()