jobs:
- deployment: Kong_Deploy
  displayName: Kong Deployment ${{ parameters.environment }}
  cancelTimeoutInMinutes: 1
  environment: ${{ parameters.environment }}
  dependsOn: UI_Deploy
  condition: and(and(not(canceled()),not(failed())), eq(variables['Kong_Deploy'],'true'))
  variables:
  - name: 'RELEASE_NAME'
    value: 'kong-gateway'
  strategy:
    runOnce:
        deploy:
            steps:
                - checkout: cicd-agent
                  clean: true
                - script: |
                    echo "Deployment of Service : kong-gateway"
                    echo;
                    echo #
                    echo "Environment variables"
                    echo #
                    echo;
                    printenv
                    echo;
                    echo;
                  displayName: 'Initialize Environment Variables'
                
                - bash: |
                    mkdir -p kong-gateway/helm/files/
                    echo "Copying Configs from CICD_Agent_Portal_cicd/kong-gateway/configs/$(ENVIRONMENT)/*"
                    cp kong-gateway/configs/$(ENVIRONMENT)/* kong-gateway/helm/files/
                    ls kong-gateway/helm/files/


                  displayName: 'Copy Config Files'

                - bash: |
                      set -x

                      helm template -n $(PROJECT) --debug --dry-run  \
                        --set-string deployment.name=$(RELEASE_NAME) \
                        $RELEASE_NAME \
                        kong-gateway/helm/
                  displayName: Helm Dry Run
                
                - bash: |
                      set -x

                      oc login --token="$(OCP4_CICDDEPLOY_TOKEN)" --server=$(OCP4_URL)

                      helm upgrade -n $(PROJECT) --install --atomic --wait --timeout 10m0s \
                        --set-string deployment.name=$(RELEASE_NAME) \
                        $RELEASE_NAME \
                        kong-gateway/helm/
                  displayName: Helm Upgrade