parameters:
- name: SERVICENAME
  type: object
- name: revisionId
  type: string
- name: revisionId_services
  type: string
- name: sourceBranch
  type: string

stages:
- stage: dev
  condition: ne(variables['Build.Reason'], 'PullRequest')
  variables:
  - group: CICD_Agent_Portal_Dev # DEV environment library variable  group
  - group: CICD ToolsTeam
  - group: CICD AdoAgents
  displayName: Deploy to Development
  pool:
    name: ocp-dot-adreport1
    demands:
      - AGENT_TYPE -equals $(AGENT_TYPE)
  jobs:
  - template: UI_deploy_template.yaml
    parameters:
      environment: 'cicd-dev'
      revisionId: ${{ parameters.revisionId }}
  - template: Kong_deploy_template.yaml
    parameters:
      environment: 'cicd-dev'
  - ${{ if containsValue(parameters.SERVICENAME, 'auth-service') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'auth-service'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'auth-service'
  - ${{ if containsValue(parameters.SERVICENAME, 'module-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'module-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'module-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'agent-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'agent-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'agent-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'team-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'team-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'team-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'pool-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'pool-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'pool-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'admin-service') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'admin-service'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'admin-service'
  - ${{ if containsValue(parameters.SERVICENAME, 'agent-pipeline') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'agent-pipeline'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-dev'
        SERVICENAME: 'agent-pipeline'
  - template: DB_deploy_template.yaml
    parameters:
      environment: 'cicd-dev'
      SERVICENAME: ${{ parameters.SERVICENAME }}
  - template: Regression_testing_template.yaml
    parameters:
      environment: 'cicd-dev'
      SERVICENAME: ${{ parameters.SERVICENAME }}

- stage: int
  dependsOn: [dev]
  variables:
  - group: CICD_Agent_Portal_INT # INT environment library variable  group
  - group: CICD ToolsTeam
  - group: CICD AdoAgents
  displayName: Deploy to INT
  pool:
    name: ocp-dot-adreport1
    demands:
      - AGENT_TYPE -equals $(AGENT_TYPE)
  jobs:
  - template: UI_deploy_template.yaml
    parameters:
      environment: 'cicd-intg'
      revisionId: ${{ parameters.revisionId }}
  - template: Kong_deploy_template.yaml
    parameters:
      environment: 'cicd-intg'
  - ${{ if containsValue(parameters.SERVICENAME, 'auth-service') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-intg'
        SERVICENAME: 'auth-service'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-intg'
        SERVICENAME: 'auth-service'
  - ${{ if containsValue(parameters.SERVICENAME, 'module-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-intg'
        SERVICENAME: 'module-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-intg'
        SERVICENAME: 'module-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'agent-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-intg'
        SERVICENAME: 'agent-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-intg'
        SERVICENAME: 'agent-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'team-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-intg'
        SERVICENAME: 'team-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-intg'
        SERVICENAME: 'team-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'pool-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-intg'
        SERVICENAME: 'pool-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-intg'
        SERVICENAME: 'pool-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'admin-service') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-intg'
        SERVICENAME: 'admin-service'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-intg'
        SERVICENAME: 'admin-service'
  - ${{ if containsValue(parameters.SERVICENAME, 'agent-pipeline') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-intg'
        SERVICENAME: 'agent-pipeline'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
  - template: DB_deploy_template.yaml
    parameters:
      environment: 'cicd-intg'
      SERVICENAME: ${{ parameters.SERVICENAME }}

- stage: staging
  dependsOn: [int]
  variables:
  - group: CICD_Agent_Portal_STG # STG environment library variable  group\
  - group: CICD ToolsTeam
  - group: CICD AdoAgents
  displayName: Deploy to Staging
  pool:
    name: ocp-dot-adreport1
    demands:
      - AGENT_TYPE -equals $(AGENT_TYPE)
  jobs:
  - template: UI_deploy_template.yaml
    parameters:
      environment: 'cicd-stg'
      revisionId: ${{ parameters.revisionId }}
  - template: Kong_deploy_template.yaml
    parameters:
      environment: 'cicd-stg'
  - ${{ if containsValue(parameters.SERVICENAME, 'auth-service') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-stg'
        SERVICENAME: 'auth-service'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-stg'
        SERVICENAME: 'auth-service'
  - ${{ if containsValue(parameters.SERVICENAME, 'module-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-stg'
        SERVICENAME: 'module-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-stg'
        SERVICENAME: 'module-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'agent-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-stg'
        SERVICENAME: 'agent-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-stg'
        SERVICENAME: 'agent-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'team-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-stg'
        SERVICENAME: 'team-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-stg'
        SERVICENAME: 'team-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'pool-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-stg'
        SERVICENAME: 'pool-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-stg'
        SERVICENAME: 'pool-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'admin-service') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-stg'
        SERVICENAME: 'admin-service'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-stg'
        SERVICENAME: 'admin-service'
  - ${{ if containsValue(parameters.SERVICENAME, 'agent-pipeline') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-stg'
        SERVICENAME: 'agent-pipeline'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
  - template: DB_deploy_template.yaml
    parameters:
      environment: 'cicd-stg'
      SERVICENAME: ${{ parameters.SERVICENAME }}

- stage: prod
  dependsOn: [staging]
  variables:
  - group: CICD_Agent_Portal_PRD # PROD environment library variable  group
  - group: CICD ToolsTeam
  - group: CICD AdoAgents
  displayName: Deploy to Production
  pool:
    name: ocp-dot-adreport1
    demands:
      - AGENT_TYPE -equals $(AGENT_TYPE)
  jobs:
  - template: UI_deploy_template.yaml
    parameters:
      environment: 'cicd-prod'
      revisionId: ${{ parameters.revisionId }}
  - template: Kong_deploy_template.yaml
    parameters:
      environment: 'cicd-prod'
  - ${{ if containsValue(parameters.SERVICENAME, 'auth-service') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-prod'
        SERVICENAME: 'auth-service'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-prod'
        SERVICENAME: 'auth-service'
  - ${{ if containsValue(parameters.SERVICENAME, 'module-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-prod'
        SERVICENAME: 'module-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-prod'
        SERVICENAME: 'module-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'agent-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-prod'
        SERVICENAME: 'agent-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-prod'
        SERVICENAME: 'agent-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'team-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-prod'
        SERVICENAME: 'team-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-prod'
        SERVICENAME: 'team-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'pool-definition') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-prod'
        SERVICENAME: 'pool-definition'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-prod'
        SERVICENAME: 'pool-definition'
  - ${{ if containsValue(parameters.SERVICENAME, 'admin-service') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-prod'
        SERVICENAME: 'admin-service'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
    - template: API_testing_template.yaml
      parameters:
        environment: 'cicd-prod'
        SERVICENAME: 'admin-service'
  - ${{ if containsValue(parameters.SERVICENAME, 'agent-pipeline') }}:
    - template: NodeJS_deploy_template.yaml
      parameters:
        environment: 'cicd-prod'
        SERVICENAME: 'agent-pipeline'
        revisionId_services: ${{ parameters.revisionId_services }}
        sourceBranch: ${{ parameters.sourceBranch }}
  - template: DB_deploy_template.yaml
    parameters:
      environment: 'cicd-prod'
      SERVICENAME: ${{ parameters.SERVICENAME }}