jobs:
- deployment: UI_Deploy
  displayName: UI Deployment ${{ parameters.environment }}
  cancelTimeoutInMinutes: 1
  environment: ${{ parameters.environment }}
  condition: and(eq(variables['UI_Deploy'],'true'), ne(variables['Build.Reason'], 'PullRequest'))
  strategy:
    runOnce:
        deploy:
            steps:
                - checkout: cicd-agent
                  fetchDepth: 0
                  clean: true
                - checkout: CICD_Agent_Portal
                - script: |
                    echo "Deployment of Service : nextjsapp"
                    echo "Environment variables"
                    printenv
                  displayName: 'Initialize Environment Variables'

                - script: |
                    #!/bin/bash
                    #As a developer, only develop/release branch can be deployed to Dev Environment. Only release branch can be deployed to all higher environments.
                    if [[ $ENVIRONMENT == 'dev' ]] ;
                    then
                            echo "This is dev hence you are allowed to deploy any branch"
                    elif [[ $ENVIRONMENT == "dev" || $ENVIRONMENT == "int"  ]] && [[ ${BUILD_SOURCEBRANCH} == "refs/heads/develop/"* || ${BUILD_SOURCEBRANCH} == "refs/heads/Develop/"* ]] ;
                    then
                            echo "Deployment Source Branch Validated"
                    elif [[ $ENVIRONMENT != 'dev' ]] && [[ ${BUILD_SOURCEBRANCH} == "refs/heads/release/"*  || ${BUILD_SOURCEBRANCH} == "refs/heads/Release/"* ]] ;
                    then
                            echo "Deployment Source Branch Validated"
                    else
                            echo "##[error] Deployment Source Branch Validation Failed. You cannot Deploy Branch ${BUILD_SOURCEBRANCH} to $ENVIRONMENT Environment."
                            exit 1
                    fi
                  displayName: 'Pre Validate Deployment Source Branch'        

                - task: CopyFiles@2
                  inputs:
                    SourceFolder: '$(System.DefaultWorkingDirectory)/CICD_Agent_Portal/configs/$(ENVIRONMENT)'
                    contents: 'baseApi.json'
                    targetFolder: "$(System.DefaultWorkingDirectory)/CICD_Agent_Portal_cicd/helm_UI/files"
                  displayName: Copy config files

                - bash: |
                      set -x
                      BUILD_BUILDID_LOWER=$(echo ${{ parameters.revisionId }} | tr '[:upper:]' '[:lower:]')
                      BUILD_SOURCEBRANCHNAME_LOWER=$(echo "$BUILD_SOURCEBRANCHNAME" | tr '[:upper:]' '[:lower:]')
                      TAG=$BUILD_BUILDID_LOWER"_"$BUILD_SOURCEBRANCHNAME_LOWER

                      helm template -n $(PROJECT) --debug --dry-run \
                        --set-string deployment.name="nextjsapp" \
                        --set-string deployment.replica=$(REPLICA) \
                        --set-string containers.repository=$(DOCKER_REGISTRY_COMMON)/cicdapp \
                        --set-string containers.nextjsapp.image.tag=$TAG \
                        --set-string containers.nextjsapp.resourceLimits.cpu=$(CPU_LIMIT) \
                        --set-string containers.nextjsapp.resourceLimits.memory=$(MEMORY_LIMIT) \
                        --set-string containers.nextjsapp.resourceRequests.cpu=$(CPU_REQUEST) \
                        --set-string containers.nextjsapp.resourceRequests.memory=$(MEMORY_REQUEST) \
                        --set-string service.ingressIp=$(INGRESS_IP) \
                        nextjsapp \
                        CICD_Agent_Portal_cicd/helm_UI/
                  displayName: Helm Dry Run

                - bash: |
                      set -x
                      BUILD_BUILDID_LOWER=$(echo ${{ parameters.revisionId }} | tr '[:upper:]' '[:lower:]')
                      BUILD_SOURCEBRANCHNAME_LOWER=$(echo "$BUILD_SOURCEBRANCHNAME" | tr '[:upper:]' '[:lower:]')
                      TAG=$BUILD_BUILDID_LOWER"_"$BUILD_SOURCEBRANCHNAME_LOWER

                      oc login --token=$(OCP4_CICDDEPLOY_TOKEN) --server=$(OCP4_URL)
                      oc project $(PROJECT)

                      helm upgrade -n $(PROJECT) --install --atomic --wait --timeout 10m0s --history-max 3 \
                        --set-string deployment.name="nextjsapp" \
                        --set-string deployment.replica=$(REPLICA) \
                        --set-string containers.repository=$(DOCKER_REGISTRY_COMMON)/cicdapp \
                        --set-string containers.nextjsapp.image.tag=$TAG \
                        --set-string containers.nextjsapp.resourceLimits.cpu=$(CPU_LIMIT) \
                        --set-string containers.nextjsapp.resourceLimits.memory=$(MEMORY_LIMIT) \
                        --set-string containers.nextjsapp.resourceRequests.cpu=$(CPU_REQUEST) \
                        --set-string containers.nextjsapp.resourceRequests.memory=$(MEMORY_REQUEST) \
                        --set-string service.ingressIp=$(INGRESS_IP) \
                        nextjsapp \
                        CICD_Agent_Portal_cicd/helm_UI/
                  displayName: Helm Upgrade